package com.liskovsoft.youtubeapi.innertube.utils

import com.liskovsoft.sharedutils.helpers.Helpers
import com.liskovsoft.youtubeapi.innertube.models.StreamingFormat
import com.liskovsoft.youtubeapi.innertube.models.CaptionTrack
import com.liskovsoft.youtubeapi.innertube.models.PlayerResult

internal fun PlayerResult.getVideoPlaybackUstreamerConfig() = playerConfig?.mediaCommonConfig?.mediaUstreamerRequestConfig?.videoPlaybackUstreamerConfig
internal fun PlayerResult.getServerAbrStreamingUrl() = streamingData?.serverAbrStreamingUrl
internal fun PlayerResult.getAdaptiveFormats() = streamingData?.adaptiveFormats
internal fun PlayerResult.getLegacyFormats() = streamingData?.formats
private fun PlayerResult.getCaptionTracks() = captions?.playerCaptionsTracklistRenderer?.captionTracks
private fun PlayerResult.getTranslationLanguages() = captions?.playerCaptionsTracklistRenderer?.translationLanguages
internal fun PlayerResult.getMergeCaptionTracks(): List<CaptionTrack>? {
    val captionsTracks = getCaptionTracks()
    val translationLanguages = getTranslationLanguages()

    if (translationLanguages != null && captionsTracks != null) {
        //CaptionTrack originTrack = findOriginTrack(mCaptionTracks);
        //String tag = Helpers.runMultiMatcher(originTrack.getName(), tagPattern);
        //for (TranslationLanguage language : mTranslationLanguages) {
        //    mMergedCaptionTracks.add(new TranslatedCaptionTrack(originTrack, language, tag));
        //}
    }
    
    return captionsTracks
}
//private CaptionTrack findOriginTrack(List<CaptionTrack> captionTracks) {
//    CaptionTrack result = null;
//
//    for (CaptionTrack track : captionTracks) {
//        if (!track.isAutogenerated()) {
//            result = track;
//            break;
//        }
//    }
//
//    return result != null ? result : captionTracks.get(0);
//}

private const val FORMAT_STREAM_TYPE_OTF = "FORMAT_STREAM_TYPE_OTF"

internal fun StreamingFormat.isBroken() = Helpers.allNulls(url, cipher, signatureCipher)
internal fun StreamingFormat.hasRange() = indexRange != null || initRange != null
internal fun StreamingFormat.getIndexRange() = indexRange?.toRangeString()
internal fun StreamingFormat.getInitRange() = initRange?.toRangeString()
internal fun StreamingFormat.isOtf() = type == FORMAT_STREAM_TYPE_OTF

internal fun StreamingFormat.Range.toRangeString() = if (start == null || end == null) "" else "$start-$end"